#
# Module manifest for module 'PSGet_PoshProgressBar'
#
# Generated by: Micah Rairdon
#
# Generated on: 11/5/2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PoshProgressBar.psm1'

# Version number of this module.
ModuleVersion = '0.134'

# Supported PSEditions (WPF/STA runspace UI: Windows PowerShell Desktop only)
CompatiblePSEditions = @('Desktop')

# ID used to uniquely identify this module
GUID = 'e6a8d048-089c-4fb0-8bf4-5e42dae30126'

# Author of this module
Author = 'Micah Rairdon'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2015-2026 Micah Rairdon. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A module for creating WPF progress bars using XAML and the Material Design Toolkit by Butchers Boy'

# Minimum version of the Windows PowerShell engine required by this module
# (5.1: WPF XAML UI, Add-Type -AssemblyName, STA runspaces; see README Compatibility)
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.0'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('MaterialDesignColors.dll', 
               'MaterialDesignThemes.Wpf.dll')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Close-ProgressBar', 'New-Progressbar', 'Write-ProgressBar'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'MaterialDesignColors.dll', 'MaterialDesignThemes.Wpf.dll', 
               'PoshProgressBar.psd1', 'PoshProgressBar.psm1', 
               'PoshProgressBar.psm1-help.xml'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('ProgressBar', 'WPF', 'XAML', 'MaterialDesign', 'Windows')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Tiberriver256/PoshProgressBar/blob/master/LICENSE.md'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Tiberriver256/PoshProgressBar'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '0.134: fixed Write-ProgressBar host-kill (exit -> warning+return); fixed $clock timer typo; fixed window Icon assignment; 0% updates no longer dropped; window options from issue #17 (Topmost/ResizeMode/ShowInTaskbar/PicturePath/ShowOnPrimaryMonitor); modern assembly loading; Gallery metadata; see CHANGELOG.md.'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

